name: "deploy"
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message,'ci:')"
    permissions: write-all
    steps:
      - name: "check out"
        uses: actions/checkout@v4
        with:
          repository: "nhannht/moonstone"
          fetch-depth: 0

      - name: setup yarn
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: install wrangler
        run: |
          yarn install
          yarn add wrangler -D

      - name: build and deploy
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          yarn build
          yarn run wrangler pages deploy







